### ISSUE TITLE
Deleting Field Service Group

### ISSUE THREAD

**Issue by ajtruckle** [ajtruckle/meeting-schedule-assistant-support#40] opened 2023-12-28 16:11 UTC
**Describe the bug**
Unable to use the Delete menu item once I have deleted (or moved) the last publisher from that group.

**To Reproduce**
Steps to reproduce the behaviour:
1. **Delete** or **Move** the last publisher for a group.
2. Click on the **Manage** button.
3. Expand the **Delete** sub-menu.
4. See error (menu item for group is still disabled).

At the moment you have to close the Publisher Database and open it again for the software to detect that there are no publishers in the group. Then you can delete the group.

**Expected behaviour**
The **Delete** sub-menu should update automatically when the _final_ publisher is deleted / moved from the group. This will enable us to delete the group without having to re-display the **Publishers Database** window.

**Comment by ajtruckle** [comment] 2024-01-11 16:01
I have made some code changes to address this issue and beta testing is underway.

**Comment by Fahdeya** [comment] 2024-01-12 13:24
I have tried the fix for this bug. It seems we have another bug. When moving a publisher from one group to another the window does not show him moved till we close and reopen the window

**Comment by cengizu** [comment] 2024-01-12 14:04
Installed Version 24.2.9 and now it seems this part of the problem is solved. However, the **Manage** button does not update itself for every action.

Tested condition:
- I create a group. [**Manage > Add Group**]
- Give it a name. [Group list got immediately updated]
- Select a publisher and assign to this new group.
It works.

Now, if you want to delete the group, it is not listed in the **Manage** list. You need to close the **Publishers Database** window and open it again to see it in the list.

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/779e0e64-a8ca-4fce-be7d-d98bbc21955a)
_**Screenshot:** Group dropdown list displays the name of the group but Manage > Delete Group does not._

**Comment by ajtruckle** [comment] 2024-01-12 15:32
@Fahdeya @cengizu 
Thanks for the feedback and I will address these issues one at a time.

@cengizu 
Please try beta 3 in the MSA Collaboration folder on Google Drive. The Edit / Delete submenus should now update immediately when you add a new group to the list.

**Comment by ajtruckle** [comment] 2024-01-12 17:13
@Fahdeya 
Please try beta 4 in the MSA Collaboration folder on Google Drive. The publisher should now be removed from the list on the left if you have moved them to a different group and are using the Group Filter.

**Comment by cengizu** [comment] 2024-01-13 08:10
Beta 3 works as expected.

Created a group > attached 1 publisher > deleted group > publisher remains unassigned. 👍

**Comment by ajtruckle** [comment] 2024-01-13 13:32
@MardoDan
Thanks to your feedback by Telegram:

> Comencé a utilizar en la Base de Datos de Publicadores la asignación a Grupo de Servicio y me di cuenta de que hay que cambiar algo: si el hermano no tiene nombramiento no se lo puede asignar como ayudante en el Grupo.

Please try beta 5 in the MSA Collaboration folder on Google Drive. You can now assigned any _baptised brother_ as a **Group Assistant**.

**Comment by MardoDan** [comment] 2024-01-13 17:37
Excelente @ajtruckle Funcionando tal lo esperado. No son muchas las veces, pero en ocasiones se necesita como ayudante a un hermano bautizado que no sea siervo ministerial.

**Closed as completed** 2024-01-15 12:48 UTC
Labels: bug
