### ISSUE TITLE
Group Editor or Manager

### ISSUE THREAD

**Issue by cengizu** [ajtruckle/meeting-schedule-assistant-support#42] opened 2024-01-15 12:16 UTC
**Is your feature request related to a problem? Please describe.**
Transferring individuals in groups from one group to another is currently handled from the Publishers Database window. Only one person can be moved at a time.

**Describe the solution you'd like**
A simple new feature allows one or more publishers to be moved from one group to another. Publishers in groups can be quickly viewed and transferred in bulk (pressing CTRL + left-click or SHIFT + left-click). 

**Here is the concept design**
The Reset button: It can also be called Cancel instead of Reset.
![image_2024-01-15_14-16-09](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/93f04822-f451-45ed-98a8-46879caf24b7)

This window can be accessed from the menu (Database > Congregations > Group Editor) and can also be accessed by a button inside the Publishers Database window. 

**As an additional idea**💡 all details of a group such as group name, conductor, assistant, field service meetings, etc. can also be edited within this window.

**Comment by ajtruckle** [comment] 2024-01-15 16:12
@cengizu 
Thanks for the suggestion. I admit that it would be handy to be able to bulk transfer publishers to different groups. Less tedious.

**Comment by ajtruckle** [comment] 2024-01-16 09:42
@cengizu 
> This window can be accessed from the menu (Database > Congregations > Group Editor) and can also be accessed by a button inside the Publishers Database window.

It could definitely be accessed from inside the Publishers Database window. But the Group data is actually stored within the Publishers database so I don't think it should be on the Congregations database sub-menu. It would be better on the Publishers sub-menu.

I wonder if the lefthand side can be simplified to display a list of all publishers (excluding the ones that are on the right in the chosen group). I don't really see any advantage in filtering the publisher list on the left of this window. Agreed?

**Comment by cengizu** [comment] 2024-01-16 10:02
@ajtruckle 

I thought having the left and right list populated using filters would provide the advantage of transferring people from one group to another. _With one condition:_ if same filter are selected in both lists (same groups) then the Add and Remove buttons are disabled.

But at the end you know better which is appropriate.

**Comment by ajtruckle** [comment] 2024-01-16 10:21
@cengizu 
Actually, you suggest a valid reason for having a filter on both sides.

**Comment by stecchio66** [comment] 2024-02-09 19:15
@ajtruckle 
The @cengizu  proposal seems good to me.

**Comment by ajtruckle** [comment] 2024-02-10 15:19
@cengizu 
I now want to think about the functionality and behaviour of this window in more detail please.

* Choose publishers from (on left)
This will have a drop-list of all known groups. The first entry will be a blank entry (like your Everyone). This makes it consistent with the existing Group drop-down lists. Selecting an entry in the list will filter the list accordingly.

* Add >>
This button will be enabled when one or more entries are selected in the left list. Clicking the button will add them to the list on the right. Please clarify / confirm:
  1. Do the names _move_ from left to right list?
  2. At what point does the actual update to the database occur? Instantly?

I am just trying to understand when the database should be updated? When you click **Done**? Ideally we don't want to be constantly saving to the database. If we can iron out all expected behaviour so I can code it accordingly.

**Comment by cengizu** [comment] 2024-02-10 19:58
@ajtruckle 
The idea is like the function in Microsoft Office (see _Customize Quick Access Toolbar Dialog_). 
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/8949d226-9a6e-40e0-9979-23b8cc01b83f)
Reference GUI Customize Quick Access Toolbar Dialog

All changes made (add/remove) are temporary until the **OK** or **Done** button is clicked, and the X (close) button and/or reset button function in the same way: terminating the operation without writing anything to the database. When the user clicks on the OK or Done button, the database write will take place.

**Comment by ajtruckle** [comment] 2024-02-10 20:03
@cengizu 
OK, so from a programming perspective I just need to keep track under the hood of all publishers who have been modified and then when they hit OK make all the updates and do a save at the end.

Leave it with me. 👍

**Comment by ajtruckle** [comment] 2024-02-11 09:14
@cengizu 
When you click Remove it will reset to original group and not whatever group is selected in left filter. Make sense?

**Comment by ajtruckle** [comment] 2024-02-11 15:38
@cengizu @stecchio66 
![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/76131133-2139-4f1a-9864-de530b572beb)
Are we getting too many **separator** lines on this menu now? Seems overkill.

**Comment by ajtruckle** [comment] 2024-02-11 17:37
@cengizu @stecchio66 
On reflection, I would like to simplify the GUI. I want the left side to have all publishers (excluding those on right). 

Only the right side has the drop list of groups. 

This approach makes it much easier as I only have to keep track of changes to the right side. I don't see any real loss in functionality by removing the filtering from the left side.

**Comment by ajtruckle** [comment] 2024-02-11 19:56
@cengizu @stecchio66 
I did some initial coding this evening. I am now thinking that we should remove the option to list all publishers on the left. So we simply allow you to go from one group to another. Otherwise the code is going to get more complicated than I would like.

Let me know if you really think we need the ability to allow the full list of publishers on the left. In which case we can discuss my logic privately.

**Comment by cengizu** [comment] 2024-02-12 11:24
> @cengizu @stecchio66 Are we getting too many **separator** lines on this menu now? Seems overkill.

These additional seperator lines at this level don't really bother the eye in my opinion. 
But you might want to consider placing this new menu entry right inside the first category (Add, Edit and Delete).

**Comment by ajtruckle** [comment] 2024-02-12 12:50
@cengizu 
I'll leave the menu as it is then. 👍 I have made more adjustments based on your feedback via Telegram.

**Comment by ajtruckle** [comment] 2024-02-12 15:39
@cengizu 
On Telegram you suggested:
> This window can also contain features such as Create Group and Delete Group. 
> 
> Expected operation:
> Delete Group > (only active when an existing group name is selected) User clicks on the Group name, clicks on the Delete Group button. All members of that group, if any, move to the Everyone group at the parent level.
> 
> Create Group > (always active button*) User clicks the button and a new, empty group is created under Everybody.
> 
> _*exception: a group cannot be created under an existing Group_

I agree that it makes sense to allow this kind of functionality but I do have some reservations:

- You can only delete a group on the Publishers Database window when the group has no assigned publishers. So I think it should work in the same way on this new Group Manager window.
- Creating a group needs to be immediately saved to the database. This is so that we can find out what the _group ID_ is for assigning to the relevant publishers.
- I think the same would apply for Deleting a group.

Understand?

**Comment by cengizu** [comment] 2024-02-13 08:03
@ajtruckle 

What about keeping all changes made in memory temporarily? When Group Editor is opened, a temporary (or a copy of the original) database structure is created. Everything will be stored in this temporary database until the OK/Finished button is pressed. When the button is pressed, this temporary database structure is fully replaced with or injected (ony the necessary parts) into the original one.

**Comment by ajtruckle** [comment] 2024-02-13 08:21
@cengizu 
In theory it is possible. I could add a group and it not be actually saved until you click ok. 

But I also feel this is a duplication of effort since we already have a GUI to add / edit / delete groups from the database.

I'll think about it. 🤔

**Comment by cengizu** [comment] 2024-02-13 08:33
@ajtruckle 

Maybe if we can handle Group management from a single point, we can avoid unnecessary complexity

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/62d4e4a7-850a-4718-bf22-fb9185465ae8)
For ex. The Manage button in this panel will open the Group Editor window. The list below the button showing which group the person belongs to works only for informational purposes. Maybe plain text instead of a list. So that the Group Editor can perform operations such as Add / Remove / Create / Delete from a single point.

**Comment by ajtruckle** [comment] 2024-02-13 08:35
@cengizu 
I'll give it some thought. 👌👍

**Comment by ajtruckle** [comment] 2024-02-13 16:57
@stecchio66 @cengizu 
After some thought and discussions together on Telegram I have ended up with the following GUI:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/7528a58f-4a7a-4ce2-9ac4-46dd4edd70b6)

I'll turn the Manage button on the Publishers Database window into a standard button now. I added a new beta on Google Drive for you to test drive.

**Comment by cengizu** [comment] 2024-02-14 08:04
![Recording 2024-02-14 110201](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/6536357/9b7f0bda-b616-495b-b391-4894a8c666b0)

Works good!

**Comment by ajtruckle** [comment] 2024-02-15 17:02
@cengizu @stecchio66 
Thanks for the video - most helpful. 😊

I have made some other refinements to the way the GUI works on the **Publishers Database** window:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/9df2be24-acf7-4a9f-8323-0d1df02aee4b)

It now has a standard **Manage** button (instead of a menu button) which displays the new **Field Service Group Manager** window.

**Comment by ajtruckle** [comment] 2024-02-16 18:17
@cengizu 
Thank you for providing some new icons for the toolbar from [www.flaticon.com](https://www.flaticon.com/):

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/5dbed07c-8f64-4f0e-aaae-39556a49e877)

It now has the new button for displaying the Field Service Group Manager. I have sent you a beta to try.

**Comment by cengizu** [comment] 2024-02-19 10:39
@ajtruckle 

Great! Everything seem fine. Thank you for all your hard work 😍

**Closed as completed** 2024-02-19 11:10 UTC
Labels: enhancement
